<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.commonprovenanceframework</groupId>
    <artifactId>cpm</artifactId>
    <version>3.0.0</version>

    <name>Common Provenance Model - Reference Implementation</name>

    <organization>
        <name>Masaryk University</name>
        <url>https://www.muni.cz/</url>
    </organization>
    <inceptionYear>2024</inceptionYear>
    <developers>
        <developer>
            <id>553651</id>
            <name>Dávid Laurovič</name>
        </developer>
    </developers>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <modules>
        <module>cpm-template</module>
        <module>cpm-core</module>
    </modules>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <openprovenance.version>2.2.0</openprovenance.version>

        <jackson.version>2.22.2</jackson.version>

        <junit.version>6.1.3</junit.version>
        <titanium-json-ld.version>1.7.0</titanium-json-ld.version>
        <jakarta.json.version>2.0.1</jakarta.json.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>cpm-core</artifactId>
                <version>${project.version}</version>
            </dependency>

            <!-- ProvToolbox -->
            <dependency>
                <groupId>org.openprovenance.prov</groupId>
                <artifactId>prov-model</artifactId>
                <version>${openprovenance.version}</version>
            </dependency>
            <dependency>
                <groupId>org.openprovenance.prov</groupId>
                <artifactId>prov-interop</artifactId>
                <version>${openprovenance.version}</version>
            </dependency>
            <dependency>
                <groupId>org.openprovenance.prov</groupId>
                <artifactId>prov-nf</artifactId>
                <version>${openprovenance.version}</version>
            </dependency>

            <!-- Jackson -->
            <dependency>
                <groupId>com.fasterxml.jackson.module</groupId>
                <artifactId>jackson-module-jsonSchema</artifactId>
                <version>${jackson.version}</version>
            </dependency>

            <!-- Test -->
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-api</artifactId>
                <version>${junit.version}</version>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-engine</artifactId>
                <version>${junit.version}</version>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter-params</artifactId>
                <version>${junit.version}</version>
            </dependency>
            <dependency>
                <groupId>com.apicatalog</groupId>
                <artifactId>titanium-json-ld</artifactId>
                <version>${titanium-json-ld.version}</version>
            </dependency>
            <dependency>
                <groupId>org.glassfish</groupId>
                <artifactId>jakarta.json</artifactId>
                <version>${jakarta.json.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
