package cz.muni.fi.cpm.template.schema;

import java.util.ArrayList;
import java.util.List;

import javax.xml.datatype.XMLGregorianCalendar;

import org.openprovenance.prov.model.Attribute;
import org.openprovenance.prov.model.QualifiedName;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyDescription;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

import cz.muni.fi.cpm.template.deserialization.AttributesDeserializer;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class MainActivity {
    @JsonProperty(required = true)
    @JsonPropertyDescription("The identifier of the activity")
    private QualifiedName id;
    @JsonPropertyDescription("The start time of the activity")
    private XMLGregorianCalendar startTime;
    @JsonPropertyDescription("The end time of the activity")
    private XMLGregorianCalendar endTime;
    @JsonPropertyDescription("The identifier of the meta bundle which is referenced by this activity")
    private QualifiedName referencedMetaBundleId;
    @JsonPropertyDescription("The content version of the referenced meta-component")
    private String referencedMetaBundleSpecV;

    @JsonDeserialize(using = AttributesDeserializer.class)
    @JsonPropertyDescription("Other arbitrary attributes in MainActivity")
    private List<Attribute> attributes;

    @JsonPropertyDescription("The identifier of the activities in domain-specific provenance, that are part of this activity")
    private List<QualifiedName> hasPart;
    @JsonPropertyDescription("The identifiers of the backward connectors that are used by this activity")
    private List<MainActivityUsed> used;
    @JsonPropertyDescription("The identifiers of the forward connectors that are generated by this activity")
    private List<QualifiedName> generated;
    @JsonPropertyDescription("The current agent this activity is associated with")
    private ConnectorAttributed associatedWith;

    public MainActivity() {
    }

    public MainActivity(QualifiedName id) {
        this.id = id;
    }

    public QualifiedName getId() {
        return id;
    }

    public void setId(QualifiedName id) {
        this.id = id;
    }

    public XMLGregorianCalendar getStartTime() {
        return startTime;
    }

    public void setStartTime(XMLGregorianCalendar startTime) {
        this.startTime = startTime;
    }

    public XMLGregorianCalendar getEndTime() {
        return endTime;
    }

    public void setEndTime(XMLGregorianCalendar endTime) {
        this.endTime = endTime;
    }

    public QualifiedName getReferencedMetaBundleId() {
        return referencedMetaBundleId;
    }

    public void setReferencedMetaBundleId(QualifiedName referencedMetaBundleId) {
        this.referencedMetaBundleId = referencedMetaBundleId;
    }

    public List<Attribute> getAttributes() {
      return this.attributes == null
          ? new ArrayList<Attribute>()
          : this.attributes;
    }

    public void setAttributes(List<Attribute> attributes) {
      this.attributes = attributes;
    }

    public String getReferencedMetaBundleSpecV() {
        return referencedMetaBundleSpecV;
    }

    public void setReferencedMetaBundleSpecV(String referencedMetaBundleSpecV) {
        this.referencedMetaBundleSpecV = referencedMetaBundleSpecV;
    }

    public List<QualifiedName> getHasPart() {
        return hasPart;
    }

    public void setHasPart(List<QualifiedName> hasPart) {
        this.hasPart = hasPart;
    }

    public List<QualifiedName> getGenerated() {
        return generated;
    }

    public void setGenerated(List<QualifiedName> generated) {
        this.generated = generated;
    }

    public ConnectorAttributed getAssociatedWith() {
        return associatedWith;
    }

    public void setAssociatedWith(ConnectorAttributed associatedWith) {
        this.associatedWith = associatedWith;
    }

    public List<MainActivityUsed> getUsed() {
        return used;
    }

    public void setUsed(List<MainActivityUsed> used) {
        this.used = used;
    }
}
